name: Auto Compress and Commit

on:
  push:
    branches:
      - Downloads  # Change if your default branch is different

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to push changes back

      - name: Install zip tool
        run: sudo apt-get install -y zip

      - name: Compress files
        run: |
          mkdir -p compressed
          zip -r compressed/archive.zip PWSKitToolsCreative
        # Example: replace "src" with the folder or files you want to compress

      - name: Move ZIP to repository root
        run: cp compressed/archive.zip ./archive.zip

      - name: Commit and push ZIP
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add archive.zip
          git commit -m "Auto compressed files on $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
